Repository ShinMyohan/MyoMiBackend, pull requests merged in 2023-03, with the labels that each got.

#128 리뷰,공지사항,관리자 수정
  .gitignore
  src/main/java/com/myomi/admin/control/AdminController.java
  src/main/java/com/myomi/admin/dto/AdminDto.java
  src/main/java/com/myomi/admin/repository/AdminRepository.java
  src/main/java/com/myomi/admin/service/AdminService.java
  src/main/java/com/myomi/notice/control/NoticeController.java
  src/main/java/com/myomi/notice/dto/NoticeDetailResponseDto.java
  src/main/java/com/myomi/notice/dto/NoticeDto.java
  src/main/java/com/myomi/notice/dto/NoticeRequestDto.java
  src/main/java/com/myomi/notice/dto/NoticeUpdateDto.java
  src/main/java/com/myomi/notice/service/NoticeService.java
  src/main/java/com/myomi/review/control/ReviewController.java
  src/main/java/com/myomi/review/dto/ReviewDetailResponseDto.java
  src/main/java/com/myomi/review/dto/ReviewReadResponseDto.java
  src/main/java/com/myomi/review/dto/ReviewSaveRequestDto.java
  src/main/java/com/myomi/review/dto/ReviewUpdateRequestDto.java
  src/main/java/com/myomi/review/entity/Review.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/s3/S3UploaderReview.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/resources/application.properties
Labels: feat

#129 일부기능 구현 & 리팩토링
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/board/dto/BoardReadResponseDto.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/board/service/BoardService.java
  src/main/java/com/myomi/comment/control/CommentController.java
  src/main/java/com/myomi/comment/dto/CommentDto.java
  src/main/java/com/myomi/comment/entity/Comment.java
  src/main/java/com/myomi/comment/repository/CommentRepository.java
  src/main/java/com/myomi/comment/service/CommentService.java
  src/main/java/com/myomi/coupon/control/CouponController.java
  src/main/java/com/myomi/coupon/dto/CouponDto.java
  src/main/java/com/myomi/coupon/entity/Coupon.java
  src/main/java/com/myomi/coupon/repository/CouponRepository.java
  src/main/java/com/myomi/coupon/service/CouponService.java
  src/main/java/com/myomi/point/control/PointDetailController.java
  src/main/java/com/myomi/point/dto/MyPageDto.java
  src/main/java/com/myomi/point/repository/PointDetailRepository.java
  src/main/java/com/myomi/point/service/PointDetailService.java
Labels: feat, refactoring

#130 리팩토링 Seller&Qna&Follow
  src/main/java/com/myomi/follow/control/FollowController.java
  src/main/java/com/myomi/follow/dto/FollowReadResponseDto.java
  src/main/java/com/myomi/follow/entity/Follow.java
  src/main/java/com/myomi/follow/repository/FollowRepository.java
  src/main/java/com/myomi/follow/service/FollowService.java
  src/main/java/com/myomi/qna/control/QnaController.java
  src/main/java/com/myomi/qna/dto/QnaAddRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaAnsRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaEditRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaPReadResponseDto.java
  src/main/java/com/myomi/qna/dto/QnaSReadResponseDto.java
  src/main/java/com/myomi/qna/dto/QnaUReadResponseDto.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/qna/service/QnaService.java
  src/main/java/com/myomi/s3/S3UploaderQna.java
  src/main/java/com/myomi/seller/control/SellerController.java
  src/main/java/com/myomi/seller/dto/SellerAddRequestDto.java
  src/main/java/com/myomi/seller/dto/SellerCheckRequestDto.java
  src/main/java/com/myomi/seller/dto/SellerDetailDto.java
  src/main/java/com/myomi/seller/dto/SellerDto.java
  src/main/java/com/myomi/seller/dto/SellerInfoResponseDto.java
  src/main/java/com/myomi/seller/dto/SellerOrderDetailDto.java
  src/main/java/com/myomi/seller/dto/SellerProductResponseDto.java
  src/main/java/com/myomi/seller/dto/SellerReadResponseDto.java
  src/main/java/com/myomi/seller/dto/SellerResponseDto.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/seller/service/SellerService.java
Labels: refactoring

#131 회원/상품 메서드 수정 및 기능 구현
  pom.xml
  src/main/java/com/myomi/MyomiJpaApplication.java
  src/main/java/com/myomi/product/control/ProductController.java
  src/main/java/com/myomi/product/dto/ProductDto.java
  src/main/java/com/myomi/product/dto/ProductReadOneDto.java
  src/main/java/com/myomi/product/dto/ProductSaveDto.java
  src/main/java/com/myomi/product/dto/ProductUpdateDto.java
  src/main/java/com/myomi/product/entity/Product.java
  src/main/java/com/myomi/product/repository/ProductRepository.java
  src/main/java/com/myomi/product/service/ProductService.java
  src/main/java/com/myomi/qna/dto/QnaPReadResponseDto.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/review/dto/ReviewReadResponseDto.java
  src/main/java/com/myomi/s3/FileUtils.java
  src/main/java/com/myomi/s3/S3Config.java
  src/main/java/com/myomi/s3/S3Uploader.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/security/util/SecurityUtil.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/dto/UserDto.java
  src/main/java/com/myomi/user/dto/UserSignUpReqeustDto.java
  src/main/java/com/myomi/user/entity/Role.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/java/com/myomi/user/repository/UserRepository.java
  src/main/java/com/myomi/user/service/UserService.java
  src/main/resources/application.properties
Labels: feat, cleanup

#133 게시판 목록에서 페이징처리 기능 추가
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/board/dto/BoardReadResponseDto.java
  src/main/java/com/myomi/board/dto/PageBean.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/board/service/BoardService.java
  src/main/java/com/myomi/comment/dto/CommentDto.java
Labels: feat

#134 리뷰 작성 , 상세보기및 수정 기능 업데이트
  src/main/java/com/myomi/admin/dto/AdminDto.java
  src/main/java/com/myomi/admin/entity/Admin.java
  src/main/java/com/myomi/admin/repository/AdminRepository.java
  src/main/java/com/myomi/admin/service/AdminService.java
  src/main/java/com/myomi/notice/dto/NoticeRequestDto.java
  src/main/java/com/myomi/notice/entity/Notice.java
  src/main/java/com/myomi/review/control/ReviewController.java
  src/main/java/com/myomi/review/dto/ReviewDetailResponseDto.java
  src/main/java/com/myomi/review/dto/ReviewReadResponseDto.java
  src/main/java/com/myomi/review/dto/ReviewSaveRequestDto.java
  src/main/java/com/myomi/review/entity/BestReview.java
  src/main/java/com/myomi/review/entity/Review.java
  src/main/java/com/myomi/review/service/ReviewService.java
Labels: feat

#135 Feat: Qnalist Paging & image upload
  src/main/java/com/myomi/follow/control/FollowController.java
  src/main/java/com/myomi/follow/service/FollowService.java
  src/main/java/com/myomi/qna/control/QnaController.java
  src/main/java/com/myomi/qna/dto/PageBean.java
  src/main/java/com/myomi/qna/dto/QnaAddRequestDto.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/qna/service/QnaService.java
  src/main/java/com/myomi/s3/S3UploaderSellerIntNum.java
  src/main/java/com/myomi/s3/S3UploaderSellerNum.java
  src/main/java/com/myomi/seller/control/SellerController.java
  src/main/java/com/myomi/seller/dto/SellerAddRequestDto.java
  src/main/java/com/myomi/seller/dto/SellerDetailDto.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/seller/service/SellerService.java
Labels: feat

#136 예외처리 추가 & 리팩토링
  src/main/java/com/myomi/cart/control/CartController.java
  src/main/java/com/myomi/cart/dto/CartReadResponseDto.java
  src/main/java/com/myomi/cart/service/CartService.java
  src/main/java/com/myomi/chat/entity/ChatMsg.java
  src/main/java/com/myomi/chat/entity/ChatRoom.java
  src/main/java/com/myomi/chat/service/ChatService.java
  src/main/java/com/myomi/common/advice/ControllerAdvice.java
  src/main/java/com/myomi/common/advice/GlobalExceptionHandler.java
  src/main/java/com/myomi/common/status/ErrorCode.java
  src/main/java/com/myomi/common/status/ErrorResponse.java
  src/main/java/com/myomi/common/status/InternalServerException.java
  src/main/java/com/myomi/common/status/NoResourceException.java
  src/main/java/com/myomi/common/status/PointValidFailedException.java
  src/main/java/com/myomi/common/status/ProductSoldOutException.java
  src/main/java/com/myomi/common/status/ResponseDetails.java
  src/main/java/com/myomi/common/status/TokenValidFailedException.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/repository/OrderCustomRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/order/service/OrderService.java
  src/main/java/com/myomi/order/service/PaymentService.java
Labels: feat, refactoring

#137 예외처리를 위한 ExceptionHandler 생성 및 일부 기능 예외처리
  src/main/java/com/myomi/common/status/AddException.java
  src/main/java/com/myomi/common/status/ExceedMaxUploadSizeException.java
  src/main/java/com/myomi/common/status/UnqualifiedException.java
  src/main/java/com/myomi/product/control/ProductController.java
  src/main/java/com/myomi/product/dto/ProductDto.java
  src/main/java/com/myomi/product/dto/ProductUpdateDto.java
  src/main/java/com/myomi/product/entity/Product.java
  src/main/java/com/myomi/product/repository/ProductRepository.java
  src/main/java/com/myomi/product/service/ProductService.java
  src/main/java/com/myomi/seller/dto/SellerProductResponseDto.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/dto/UserDto.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/java/com/myomi/user/service/UserService.java
Labels: feat, refactoring

#138 게시판 예외처리 추가
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/board/service/BoardService.java
  src/main/java/com/myomi/comment/control/CommentController.java
  src/main/java/com/myomi/comment/repository/CommentRepository.java
  src/main/java/com/myomi/comment/service/CommentService.java
  src/main/java/com/myomi/coupon/control/CouponController.java
  src/main/java/com/myomi/coupon/service/CouponService.java
  src/main/java/com/myomi/point/control/PointDetailController.java
  src/main/java/com/myomi/point/service/PointDetailService.java
  src/main/java/com/myomi/s3/S3UploaderBoard.java
Labels: upgrade

#140 문자인증 Service, Controller 추가 및 User 기능 보완/예외처리 추가
  .gitignore
  pom.xml
  src/main/java/com/myomi/product/control/ProductController.java
  src/main/java/com/myomi/product/dto/ProductDto.java
  src/main/java/com/myomi/product/dto/ProductReadOneDto.java
  src/main/java/com/myomi/product/dto/ProductUpdateDto.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/java/com/myomi/user/service/CertificationSevice.java
  src/main/java/com/myomi/user/service/UserService.java
  src/main/resources/application.properties
Labels: feat

#141 문의 페이징 수정 & 판매자 일부 기능 보완
  src/main/java/com/myomi/follow/repository/FollowRepository.java
  src/main/java/com/myomi/qna/control/QnaController.java
  src/main/java/com/myomi/qna/dto/PageBean.java
  src/main/java/com/myomi/qna/dto/QnaEditRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaPReadResponseDto.java
  src/main/java/com/myomi/qna/dto/QnaUReadResponseDto.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/qna/service/QnaService.java
  src/main/java/com/myomi/s3/S3UploaderQna.java
  src/main/java/com/myomi/seller/control/SellerController.java
  src/main/java/com/myomi/seller/dto/SellerOrderDetailDto.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/seller/service/SellerService.java
Labels: feat

#142 예외처리 & 주석제거 & 채팅기능 추가 구현
  src/main/java/com/myomi/cart/control/CartController.java
  src/main/java/com/myomi/cart/dto/CartDeleteRequestDto.java
  src/main/java/com/myomi/cart/dto/CartSaveRequestDto.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/service/CartService.java
  src/main/java/com/myomi/chat/controller/MsgController.java
  src/main/java/com/myomi/chat/controller/RoomController.java
  src/main/java/com/myomi/chat/dto/ChatMsgRequestDto.java
  src/main/java/com/myomi/chat/dto/ChatMsgResponseDto.java
  src/main/java/com/myomi/chat/dto/ChatRoomDto.java
  src/main/java/com/myomi/chat/dto/ChatRoomListDto.java
  src/main/java/com/myomi/chat/entity/ChatMsg.java
  src/main/java/com/myomi/chat/entity/ChatMsgEmbedded.java
  src/main/java/com/myomi/chat/entity/ChatRoom.java
  src/main/java/com/myomi/chat/repository/ChatMsgRepository.java
  src/main/java/com/myomi/chat/repository/ChatRepository.java
  src/main/java/com/myomi/chat/service/ChatService.java
  src/main/java/com/myomi/common/advice/ControllerAdvice.java
  src/main/java/com/myomi/common/advice/GlobalExceptionHandler.java
  src/main/java/com/myomi/common/config/SocketConfig.java
  src/main/java/com/myomi/common/status/PointValidFailedException.java
  src/main/java/com/myomi/coupon/service/CouponService.java
  src/main/java/com/myomi/exception/AddException.java
  src/main/java/com/myomi/exception/FindException.java
  src/main/java/com/myomi/exception/RemoveException.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/control/PaymentController.java
  src/main/java/com/myomi/order/dto/DeliveryRequestDto.java
  src/main/java/com/myomi/order/dto/OrderDetailRequestDto.java
  src/main/java/com/myomi/order/dto/OrderRequestDto.java
  src/main/java/com/myomi/order/entity/Order.java
  src/main/java/com/myomi/order/entity/OrderDetail.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/order/service/OrderService.java
  src/main/java/com/myomi/order/service/PaymentService.java
  src/main/java/com/myomi/security/SecurityConfig.java
Labels: feat, refactoring, cleanup, upgrade

#143 장바구니 기능 보완
  src/main/java/com/myomi/cart/dto/CartSaveRequestDto.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/service/CartService.java
  src/main/java/com/myomi/order/repository/OrderCustomRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
Labels: refactoring, cleanup

#144 셀러 승인시 문자로 알림 기능 추가 등
  src/main/java/com/myomi/qna/control/QnaController.java
  src/main/java/com/myomi/qna/dto/QnaPReadResponseDto.java
  src/main/java/com/myomi/qna/service/QnaService.java
  src/main/java/com/myomi/seller/dto/SellerDetailDto.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/service/CertificationSevice.java
Labels: feat

#145 필요없는 예외 , 리포지토리 메서드 , 시큐리티 컨피그 수정
  src/main/java/com/myomi/admin/control/AdminController.java
  src/main/java/com/myomi/admin/repository/AdminRepository.java
  src/main/java/com/myomi/admin/service/AdminService.java
  src/main/java/com/myomi/notice/service/NoticeService.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
Labels: feat

#146 미사용 어노테이션 제거
  src/main/java/com/myomi/cart/control/CartController.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/entity/CartEmbedded.java
  src/main/java/com/myomi/chat/entity/ChatMsg.java
Labels: cleanup

#147 리뷰 작성 기능 수정 및 상품 베스트리뷰 출력 기능, 공지사항과 리뷰 최신순 정렬 구현
  src/main/java/com/myomi/admin/service/AdminService.java
  src/main/java/com/myomi/notice/repository/NoticeRepository.java
  src/main/java/com/myomi/notice/service/NoticeService.java
  src/main/java/com/myomi/product/dto/ProductReadOneDto.java
  src/main/java/com/myomi/product/service/ProductService.java
  src/main/java/com/myomi/review/dto/ReviewDetailResponseDto.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/s3/S3UploaderReview.java
Labels: feat, fix
