Repository ShinMyohan/MyoMiBackend, pull requests merged in 2023-01, with the labels that each got.

#11 Order DAO 생성
  resources/mybatis-config.xml
  resources/mybatis-mapper.xml
  src/main/java/com/myomi/order/dao/OrderDAO.java
  src/main/java/com/myomi/order/dao/OrderDAOOracle.java
  src/main/java/com/myomi/order/dao/order.xml
  src/main/java/com/myomi/resources/Factory.java
  src/main/java/com/myomi/resources/config.xml
Labels: feat

#21 커뮤니티 기능 구현
  src/main/java/com/myomi/board/dao/BoardDAO.java
  src/main/java/com/myomi/board/dao/BoardDAOOracle.java
  src/main/java/com/myomi/board/dao/board.xml
  src/main/java/com/myomi/comment/dao/CommentDAO.java
  src/main/java/com/myomi/comment/dao/CommentDAOOracle.java
  src/main/java/com/myomi/comment/dao/comment.xml
  src/main/java/com/myomi/common/MyBatisTestApp01.java
  src/main/java/com/myomi/dto/PageBean.java
  src/main/java/com/myomi/membership/dao/MembershipDAO.java
  src/main/java/com/myomi/membership/dao/MembershipDAOOracle.java
  src/main/java/com/myomi/membership/dao/membership.xml
  src/main/java/com/myomi/product/dao/ProductDAOOracle.java
  src/main/java/com/myomi/resource/config.xml
Labels: feat

#22 리뷰 / 포인트 기능 구현
  src/main/java/com/myomi/point/dao/PointDAOOracle.java
  src/main/java/com/myomi/point/dao/PointDao.java
  src/main/java/com/myomi/point/dao/point.xml
  src/main/java/com/myomi/review/control/ListByStarsController.java
  src/main/java/com/myomi/review/control/ReviewController.java
  src/main/java/com/myomi/review/dao/ReviewDAO.java
  src/main/java/com/myomi/review/dao/ReviewDAOOracle.java
  src/main/java/com/myomi/review/dao/review.xml
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/review/vo/BestReviewVo.java
Labels: feat

#24 회원 기능 구현
  resources/mybatis-config.xml
  src/main/java/com/myomi/exception/AddException.java
  src/main/java/com/myomi/membership/dao/webapp/user.properties
  src/main/java/com/myomi/resource/Factory.java
  src/main/java/com/myomi/resource/config.xml
  src/main/java/com/myomi/user/control/FindAllUserController.java
  src/main/java/com/myomi/user/control/ListController.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/dao/UserDAO.java
  src/main/java/com/myomi/user/dao/UserDAOOracle.java
  src/main/java/com/myomi/user/dao/user.xml
  src/main/java/com/myomi/user/service/UserService.java
  src/main/java/com/myomi/user/vo/UserVo.java
Labels: feat

#25 쿠폰 기능 구현
  .gitignore
  src/main/java/com/myomi/coupon/control/CouponController.java
  src/main/java/com/myomi/coupon/control/ListController.java
  src/main/java/com/myomi/coupon/dao/CouponDAO.java
  src/main/java/com/myomi/coupon/dao/CouponDAOOracle.java
  src/main/java/com/myomi/coupon/dao/coupon.xml
  src/main/java/com/myomi/coupon/service/CouponService.java
  src/main/java/com/myomi/order/dao/OrderDAOOracle.java
  src/main/java/com/myomi/resource/config.xml
  src/main/java/com/myomi/resources/Factory.java
  src/main/java/com/myomi/resources/config.xml
  src/main/webapp/coupon.properties
Labels: feat

#35 상품 service, controller, properties 구현
  src/main/java/com/myomi/product/control/AddController.java
  src/main/java/com/myomi/product/control/InfoController.java
  src/main/java/com/myomi/product/control/ListByCategoryController.java
  src/main/java/com/myomi/product/control/ListController.java
  src/main/java/com/myomi/product/control/ModifyController.java
  src/main/java/com/myomi/product/control/ProductController.java
  src/main/java/com/myomi/product/dao/ProductDAO.java
  src/main/java/com/myomi/product/dao/ProductDAOOracle.java
  src/main/java/com/myomi/product/dao/product.xml
  src/main/java/com/myomi/product/service/ProductService.java
  src/main/webapp/product.properties
Labels: feat

#43 커뮤니티 dao, service, controller 구현
  src/main/java/com/myomi/board/control/AddController.java
  src/main/java/com/myomi/board/control/AttachServlet.java
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/board/control/CategoryController.java
  src/main/java/com/myomi/board/control/DelController.java
  src/main/java/com/myomi/board/control/FindByTitleController.java
  src/main/java/com/myomi/board/control/FindDetailController.java
  src/main/java/com/myomi/board/control/ListController.java
  src/main/java/com/myomi/board/control/ModifyController.java
  src/main/java/com/myomi/board/dao/BoardDAO.java
  src/main/java/com/myomi/board/dao/BoardDAOOracle.java
  src/main/java/com/myomi/board/dao/board.xml
  src/main/java/com/myomi/board/service/BoardService.java
  src/main/java/com/myomi/board/vo/BoardVo.java
  src/main/java/com/myomi/comment/vo/CommentVo.java
  src/main/java/com/myomi/order/dao/OrderDAOOracle.java
  src/main/java/com/myomi/resource/config.xml
  src/main/webapp/board.properties
Labels: feat

#48 장바구니 전체적인 기능 구현
  src/main/java/com/myomi/cart/control/AddController.java
  src/main/java/com/myomi/cart/control/CartController.java
  src/main/java/com/myomi/cart/control/ListController.java
  src/main/java/com/myomi/cart/control/ModifyController.java
  src/main/java/com/myomi/cart/control/RemoveController.java
  src/main/java/com/myomi/cart/dao/CartDAO.java
  src/main/java/com/myomi/cart/dao/CartDAOOracle.java
  src/main/java/com/myomi/cart/dao/cart.xml
  src/main/java/com/myomi/cart/service/CartService.java
  src/main/webapp/cart.properties
Labels: feat

#50 Feat: 리뷰작성 컨트롤러 및 포인트 조회 컨트롤러및 리뷰상세조회 컨트롤러 구현
  src/main/java/com/myomi/point/control/ListPointController.java
  src/main/java/com/myomi/point/control/PointController.java
  src/main/java/com/myomi/point/dao/PointDAOOracle.java
  src/main/java/com/myomi/review/control/AddReviewController.java
  src/main/java/com/myomi/review/control/DetailReviewController.java
Labels: feat

#52 장바구니 목록 불러오기 기능 업데이트
  src/main/java/com/myomi/cart/dao/CartDAOOracle.java
  src/main/java/com/myomi/cart/dao/cart.xml
  src/main/webapp/user.properties
Labels: feat, refactoring

#53 Feat: board mapper 쿼리 일부 수정
  src/main/java/com/myomi/board/dao/board.xml
Labels: feat

#54 주문 기능 업데이트
  src/main/java/com/myomi/coupon/dao/coupon.xml
  src/main/java/com/myomi/order/control/DeliveryController.java
  src/main/java/com/myomi/order/control/DetailController.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/control/PaymentController.java
  src/main/java/com/myomi/order/dao/OrderDAOOracle.java
  src/main/java/com/myomi/order/dao/order.xml
  src/main/java/com/myomi/order/service/OrderService.java
  src/main/java/com/myomi/order/vo/DeliveryVo.java
  src/main/java/com/myomi/order/vo/OrderVo.java
Labels: feat

#56 필요없는 주석 제거, 필요한 주석 추가, 다오 오라클 변수명 통일
  src/main/java/com/myomi/point/control/PointController.java
  src/main/java/com/myomi/point/dao/PointDAOOracle.java
  src/main/java/com/myomi/review/dao/ReviewDAOOracle.java
  src/main/java/com/myomi/review/service/ReviewService.java
Labels: cleanup
