Repository ShinMyohan/MyoMiBackend, pull requests merged in 2023-02, with the labels that each got.

#58 User/Product 엔티티와 Spring Security JWT + Refresh Token 설정파일
  .gitignore
  pom.xml
  src/main/java/com/myomi/MyomiJpaApplication.java
  src/main/java/com/myomi/jwt/dto/TokenDto.java
  src/main/java/com/myomi/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/myomi/jwt/provider/JwtTokenProvider.java
  src/main/java/com/myomi/product/entity/Product.java
  src/main/java/com/myomi/product/repository/ProductRepository.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/security/user/CustomUserDetailsService.java
  src/main/java/com/myomi/security/util/SecurityUtil.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/dto/UserLoginRequestDto.java
  src/main/java/com/myomi/user/entity/Membership.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/java/com/myomi/user/entity/UserRole.java
  src/main/java/com/myomi/user/repository/UserRepository.java
  src/main/java/com/myomi/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/myomi/repository/ProductRepoTest.java
  src/test/java/com/myomi/repository/UserRepoTest.java
Labels: feat

#59 게시판/댓글/포인트/쿠폰 엔티티 생성
  pom.xml
  src/main/java/com/myomi/MyomiJpaApplication.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/comment/entity/Comment.java
  src/main/java/com/myomi/comment/repository/CommentRepository.java
  src/main/java/com/myomi/coupon/entity/Coupon.java
  src/main/java/com/myomi/coupon/repository/CouponRepository.java
  src/main/java/com/myomi/point/entity/Point.java
  src/main/java/com/myomi/point/entity/PointDetail.java
  src/main/java/com/myomi/point/entity/PointDetailEmbedded.java
  src/main/java/com/myomi/point/repository/PointDetailRepository.java
  src/main/java/com/myomi/point/repository/PointRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/log4jdbc.log4j2.properties
  src/test/java/com/myomi/repotest/BoardRepositoryTest.java
  src/test/java/com/myomi/repotest/CommentsRepoTest.java
  src/test/java/com/myomi/repotest/CouponRepoTest.java
  src/test/java/com/myomi/repotest/PointRepoTest.java
Labels: feat

#61 Seller/Qna/Follow 엔티티 생성
  pom.xml
  src/main/java/com/myomi/follow/entity/Follow.java
  src/main/java/com/myomi/follow/entity/FollowEmbedded.java
  src/main/java/com/myomi/follow/repository/FollowRepository.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/resources/application.properties
  src/main/webapp/user.properties
  src/test/java/com/myomi/repository/FollowRepositoryTest.java
  src/test/java/com/myomi/repository/ProductRepositoryTest.java
  src/test/java/com/myomi/repository/QnaRepositoryTest.java
  src/test/java/com/myomi/repository/SellerRepositoryTest.java
  src/test/java/com/myomi/repository/UserRepoTest.java
Labels: feat

#62 Review/Notice/BestReview/Admin 엔티티 생성
  pom.xml
  src/main/java/com/myomi/admin/entity/Admin.java
  src/main/java/com/myomi/admin/repository/AdminRepository.java
  src/main/java/com/myomi/notice/entity/Notice.java
  src/main/java/com/myomi/notice/repository/NoticeRepository.java
  src/main/java/com/myomi/review/entity/BestReview.java
  src/main/java/com/myomi/review/entity/Review.java
  src/main/java/com/myomi/review/repository/BestReviewRepository.java
  src/main/java/com/myomi/review/repository/OrderRepository.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/test/java/com/myomi/repository/AdminRepoTest.java
  src/test/java/com/myomi/repository/NoticeRepoTest.java
  src/test/java/com/myomi/repository/ReviewRepoTest.java
Labels: feat

#118 게시판/댓글/쿠폰/포인트 Dto/Service/Controller 생성
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/board/dto/BoardDetailResponseDto.java
  src/main/java/com/myomi/board/dto/BoardReadResponseDto.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/board/service/BoardService.java
  src/main/java/com/myomi/comment/control/CommentController.java
  src/main/java/com/myomi/comment/dto/CommentDto.java
  src/main/java/com/myomi/comment/entity/Comment.java
  src/main/java/com/myomi/comment/repository/CommentRepository.java
  src/main/java/com/myomi/comment/service/CommentService.java
  src/main/java/com/myomi/coupon/control/CouponController.java
  src/main/java/com/myomi/coupon/dto/CouponDto.java
  src/main/java/com/myomi/coupon/entity/Coupon.java
  src/main/java/com/myomi/coupon/repository/CouponRepository.java
  src/main/java/com/myomi/coupon/service/CouponService.java
  src/main/java/com/myomi/point/control/PointDetailController.java
  src/main/java/com/myomi/point/dto/PointDetailDto.java
  src/main/java/com/myomi/point/dto/PointDetailEmbeddedDto.java
  src/main/java/com/myomi/point/dto/PointDto.java
  src/main/java/com/myomi/point/entity/Point.java
  src/main/java/com/myomi/point/entity/PointDetail.java
  src/main/java/com/myomi/point/entity/PointDetailEmbedded.java
  src/main/java/com/myomi/point/repository/PointDetailRepository.java
  src/main/java/com/myomi/point/repository/PointRepository.java
  src/main/java/com/myomi/point/service/PointDetailService.java
Labels: feat

#119 회원/상품 Controller/Sevice/Dto
  .gitignore
  pom.xml
  src/main/java/com/myomi/admin/entity/Admin.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/repository/CartRepository.java
  src/main/java/com/myomi/common/config/SwaggerConfig.java
  src/main/java/com/myomi/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/myomi/membership/entity/Membership.java
  src/main/java/com/myomi/notice/entity/Notice.java
  src/main/java/com/myomi/order/entity/Delivery.java
  src/main/java/com/myomi/order/entity/Order.java
  src/main/java/com/myomi/order/entity/OrderDetail.java
  src/main/java/com/myomi/order/entity/OrderDetailEmbedded.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/product/control/ProductController.java
  src/main/java/com/myomi/product/dto/ProductDto.java
  src/main/java/com/myomi/product/dto/ProductReadOneDto.java
  src/main/java/com/myomi/product/dto/ProductSaveDto.java
  src/main/java/com/myomi/product/dto/ProductUpdateDto.java
  src/main/java/com/myomi/product/entity/Product.java
  src/main/java/com/myomi/product/repository/ProductRepository.java
  src/main/java/com/myomi/product/service/ProductService.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/review/entity/BestReview.java
  src/main/java/com/myomi/review/entity/Review.java
  src/main/java/com/myomi/review/repository/OrderRepository.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/security/user/CustomUserDetailsService.java
  src/main/java/com/myomi/seller/dto/SellerDto.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/user/control/UserController.java
  src/main/java/com/myomi/user/dto/UserDto.java
  src/main/java/com/myomi/user/dto/UserSignUpReqeustDto.java
  src/main/java/com/myomi/user/entity/Membership.java
  src/main/java/com/myomi/user/entity/Role.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/java/com/myomi/user/entity/UserRole.java
  src/main/java/com/myomi/user/repository/UserRepository.java
  src/main/java/com/myomi/user/service/UserService.java
  src/main/resources/application.properties
  src/test/java/com/myomi/repository/CartRepoTest.java
  src/test/java/com/myomi/repository/OrderRepoTest.java
  src/test/java/com/myomi/repository/Password.java
  src/test/java/com/myomi/repository/ProductRepositoryTest.java
  src/test/java/com/myomi/repository/QnaRepositoryTest.java
  src/test/java/com/myomi/repository/SellerRepositoryTest.java
  src/test/java/com/myomi/repository/UserRepoTest.java
  src/test/java/com/myomi/repotest/BoardRepositoryTest.java
  src/test/java/com/myomi/repotest/CommentsRepoTest.java
  src/test/java/com/myomi/repotest/CouponRepoTest.java
  src/test/java/com/myomi/repotest/PointRepoTest.java
Labels: feat

#120 문의/판매자/팔로우 Controller/Service/Dto
  src/main/java/com/myomi/follow/control/FollowController.java
  src/main/java/com/myomi/follow/dto/FollowDeleteRequestDto.java
  src/main/java/com/myomi/follow/dto/FollowReadResponseDto.java
  src/main/java/com/myomi/follow/entity/Follow.java
  src/main/java/com/myomi/follow/entity/FollowEmbedded.java
  src/main/java/com/myomi/follow/repository/FollowRepository.java
  src/main/java/com/myomi/follow/service/FollowService.java
  src/main/java/com/myomi/qna/control/QnaController.java
  src/main/java/com/myomi/qna/dto/QnaAddRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaAnsRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaEditRequestDto.java
  src/main/java/com/myomi/qna/dto/QnaPReadResponseDto.java
  src/main/java/com/myomi/qna/dto/QnaSReadResponseDto.java
  src/main/java/com/myomi/qna/dto/QnaUReadResponseDto.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/qna/repository/QnaRepository.java
  src/main/java/com/myomi/qna/service/QnaService.java
  src/main/java/com/myomi/seller/control/SellerController.java
  src/main/java/com/myomi/seller/dto/SellerAddRequestDto.java
  src/main/java/com/myomi/seller/dto/SellerInfoResponseDto.java
  src/main/java/com/myomi/seller/dto/SellerOrderDetailDto.java
  src/main/java/com/myomi/seller/dto/SellerReadResponseDto.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/seller/service/SellerService.java
Labels: feat

#121 리뷰/공지사항/관리자 Controller/Service/Dto
  pom.xml
  src/main/java/com/myomi/admin/control/AdminController.java
  src/main/java/com/myomi/admin/dto/AdminDto.java
  src/main/java/com/myomi/admin/dto/SellerDetailDto.java
  src/main/java/com/myomi/admin/dto/SellerResponseDto.java
  src/main/java/com/myomi/admin/entity/Admin.java
  src/main/java/com/myomi/admin/repository/AdminRepository.java
  src/main/java/com/myomi/admin/service/AdminService.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/entity/CartEmbedded.java
  src/main/java/com/myomi/cart/repository/CartRepository.java
  src/main/java/com/myomi/comment/repository/CommentRepository.java
  src/main/java/com/myomi/config/SwaggerConfig.java
  src/main/java/com/myomi/coupon/repository/CouponRepository.java
  src/main/java/com/myomi/jwt/provider/JwtTokenProvider.java
  src/main/java/com/myomi/notice/control/NoticeController.java
  src/main/java/com/myomi/notice/dto/NoticeDetailResponseDto.java
  src/main/java/com/myomi/notice/dto/NoticeDto.java
  src/main/java/com/myomi/notice/dto/NoticeRequestDto.java
  src/main/java/com/myomi/notice/dto/NoticeUpdateDto.java
  src/main/java/com/myomi/notice/entity/Notice.java
  src/main/java/com/myomi/notice/repository/NoticeRepository.java
  src/main/java/com/myomi/notice/service/NoticeService.java
  src/main/java/com/myomi/order/dto/OrderDetailDto.java
  src/main/java/com/myomi/order/entity/Delivery.java
  src/main/java/com/myomi/order/entity/Order.java
  src/main/java/com/myomi/order/entity/OrderDetail.java
  src/main/java/com/myomi/order/entity/OrderDetailEmbedded.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/review/control/ReviewController.java
  src/main/java/com/myomi/review/dto/ReviewDetailResponseDto.java
  src/main/java/com/myomi/review/dto/ReviewReadResponseDto.java
  src/main/java/com/myomi/review/dto/ReviewSaveRequestDto.java
  src/main/java/com/myomi/review/dto/ReviewUpdateRequestDto.java
  src/main/java/com/myomi/review/entity/BestReview.java
  src/main/java/com/myomi/review/entity/Review.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/java/com/myomi/user/repository/UserRepository.java
  src/test/java/com/myomi/repository/CartRepoTest.java
  src/test/java/com/myomi/repository/FollowRepositoryTest.java
  src/test/java/com/myomi/repository/NoticeRepoTest.java
  src/test/java/com/myomi/repository/OrderRepoTest.java
  src/test/java/com/myomi/repository/ProductRepoTest.java
  src/test/java/com/myomi/repository/QnaRepositoryTest.java
  src/test/java/com/myomi/repository/ReviewRepoTest.java
  src/test/java/com/myomi/repository/SellerRepositoryTest.java
  src/test/java/com/myomi/repository/UserRepoTest.java
  src/test/java/com/myomi/repotest/BoardRepositoryTest.java
  src/test/java/com/myomi/repotest/CommentsRepoTest.java
  src/test/java/com/myomi/repotest/CouponRepoTest.java
  src/test/java/com/myomi/repotest/PointRepoTest.java
Labels: feat

#122 장바구니 & 주문 기능 구현
  .gitignore
  pom.xml
  src/main/java/com/myomi/QuerydslConfig.java
  src/main/java/com/myomi/admin/entity/Admin.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/cart/control/CartController.java
  src/main/java/com/myomi/cart/dto/CartDeleteRequestDto.java
  src/main/java/com/myomi/cart/dto/CartReadResponseDto.java
  src/main/java/com/myomi/cart/dto/CartSaveRequestDto.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/repository/CartRepository.java
  src/main/java/com/myomi/cart/service/CartService.java
  src/main/java/com/myomi/comment/entity/Comment.java
  src/main/java/com/myomi/comment/repository/CommentRepository.java
  src/main/java/com/myomi/config/SwaggerConfig.java
  src/main/java/com/myomi/coupon/entity/Coupon.java
  src/main/java/com/myomi/coupon/repository/CouponRepository.java
  src/main/java/com/myomi/notice/entity/Notice.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/dto/DeliveryRequestDto.java
  src/main/java/com/myomi/order/dto/OrderDetailDto.java
  src/main/java/com/myomi/order/dto/OrderDetailRequestDto.java
  src/main/java/com/myomi/order/dto/OrderRequestDto.java
  src/main/java/com/myomi/order/dto/OrderResponseDto.java
  src/main/java/com/myomi/order/dto/PaymentRequestDto.java
  src/main/java/com/myomi/order/entity/Delivery.java
  src/main/java/com/myomi/order/entity/Order.java
  src/main/java/com/myomi/order/entity/OrderDetail.java
  src/main/java/com/myomi/order/entity/OrderDetailEmbedded.java
  src/main/java/com/myomi/order/repository/OrderCustomRepository.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/order/service/OrderService.java
  src/main/java/com/myomi/point/control/PointDetailController.java
  src/main/java/com/myomi/product/repository/ProductRepository.java
  src/main/java/com/myomi/qna/entity/Qna.java
  src/main/java/com/myomi/review/entity/BestReview.java
  src/main/java/com/myomi/review/entity/Review.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/security/user/CustomUserDetailsService.java
  src/main/java/com/myomi/security/util/SecurityUtil.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/user/entity/User.java
  src/main/resources/application.properties
  src/test/java/com/myomi/repository/CartRepoTest.java
  src/test/java/com/myomi/repository/OrderRepoTest.java
  src/test/java/com/myomi/repository/QnaRepositoryTest.java
  src/test/java/com/myomi/repository/UserRepoTest.java
  src/test/java/com/myomi/repotest/BoardRepositoryTest.java
  src/test/java/com/myomi/repotest/CommentsRepoTest.java
  src/test/java/com/myomi/repotest/CouponRepoTest.java
  src/test/java/com/myomi/repotest/PointRepoTest.java
Labels: feat

#123 주문 / 장바구니 기능 수정
  src/main/java/com/myomi/cart/control/CartController.java
  src/main/java/com/myomi/cart/dto/CartSaveRequestDto.java
  src/main/java/com/myomi/cart/entity/Cart.java
  src/main/java/com/myomi/cart/entity/CartEmbedded.java
  src/main/java/com/myomi/cart/repository/CartRepository.java
  src/main/java/com/myomi/cart/service/CartService.java
  src/main/java/com/myomi/config/SwaggerConfig.java
  src/main/java/com/myomi/exception/AddException.java
  src/main/java/com/myomi/exception/FindException.java
  src/main/java/com/myomi/exception/RemoveException.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/dto/OrderDetailDto.java
  src/main/java/com/myomi/order/dto/OrderResponseDto.java
  src/main/java/com/myomi/order/entity/OrderDetail.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/order/service/OrderService.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/test/java/com/myomi/repository/CartRepoTest.java
  src/test/java/com/myomi/repository/OrderRepoTest.java
  src/test/java/com/myomi/repository/ProductRepositoryTest.java
Labels: fix, refactoring

#124 합친 후 User/Product 확인 후 PR
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/repository/OrderDetailRepository.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/order/service/OrderService.java
  src/main/java/com/myomi/point/entity/PointDetail.java
  src/main/java/com/myomi/product/control/ProductController.java
  src/main/java/com/myomi/product/dto/ProductDto.java
  src/main/java/com/myomi/product/dto/ProductReadOneDto.java
  src/main/java/com/myomi/product/service/ProductService.java
  src/main/java/com/myomi/review/control/ReviewController.java
  src/main/java/com/myomi/review/dto/ReviewSaveRequestDto.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/security/SecurityConfig.java
  src/main/java/com/myomi/seller/dto/SellerOrderDetailDto.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/seller/service/SellerService.java
  src/main/java/com/myomi/user/service/UserService.java
  src/test/java/com/myomi/repository/OrderRepoTest.java
  src/test/java/com/myomi/repository/ProductRepositoryTest.java
  src/test/java/com/myomi/repository/SellerRepositoryTest.java
Labels: feat, fix

#125 게시판, 댓글, 포인트 메서드명 변경
  src/main/java/com/myomi/board/control/BoardController.java
  src/main/java/com/myomi/board/dto/BoardReadResponseDto.java
  src/main/java/com/myomi/board/entity/Board.java
  src/main/java/com/myomi/board/repository/BoardRepository.java
  src/main/java/com/myomi/board/service/BoardService.java
  src/main/java/com/myomi/comment/control/CommentController.java
  src/main/java/com/myomi/comment/dto/CommentDto.java
  src/main/java/com/myomi/comment/entity/Comment.java
  src/main/java/com/myomi/comment/service/CommentService.java
  src/main/java/com/myomi/order/control/OrderController.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/point/control/PointDetailController.java
Labels: fix, refactoring

#126 문의/판매자/팔로우 메서드명 변경
  src/main/java/com/myomi/follow/control/FollowController.java
  src/main/java/com/myomi/follow/service/FollowService.java
  src/main/java/com/myomi/order/repository/OrderRepository.java
  src/main/java/com/myomi/order/repository/OrderRepositoryImpl.java
  src/main/java/com/myomi/qna/control/QnaController.java
  src/main/java/com/myomi/qna/dto/QnaEditRequestDto.java
  src/main/java/com/myomi/qna/service/QnaService.java
  src/main/java/com/myomi/seller/control/SellerController.java
  src/main/java/com/myomi/seller/entity/Seller.java
  src/main/java/com/myomi/seller/repository/SellerRepository.java
  src/main/java/com/myomi/seller/service/SellerService.java
Labels: feat

#127 리뷰/관리자/공지사항 메서드명 변경
  src/main/java/com/myomi/admin/control/AdminController.java
  src/main/java/com/myomi/admin/service/AdminService.java
  src/main/java/com/myomi/notice/control/NoticeController.java
  src/main/java/com/myomi/notice/service/NoticeService.java
  src/main/java/com/myomi/review/control/ReviewController.java
  src/main/java/com/myomi/review/dto/ReviewReadResponseDto.java
  src/main/java/com/myomi/review/repository/ReviewRepository.java
  src/main/java/com/myomi/review/service/ReviewService.java
  src/main/java/com/myomi/seller/dto/SellerDetailDto.java
  src/main/java/com/myomi/seller/dto/SellerResponseDto.java
Labels: feat
